targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
      method_to_swagger_yaml|swaggerYamlBuilder:
        options:
          build_extensions:
            ".dart": ".yaml.dart"
