name: method_to_swagger_yaml
description: "method to swagger yaml."
version: 0.0.1
repository: https://github.com/powerboo/method_to_swagger_yaml

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  build: ^2.3.1
  analyzer: ^5.7.1
  source_gen: ^1.2.7
  code_builder: ^4.4.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  method_to_swagger_yaml_annotation: ^0.0.1
  source_gen_test: ^1.0.6

dev_dependencies:
  build_runner: ^2.3.3
  test: ^1.21.0
  path: ^1.9.0
